paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: cleo
google_analytics: cleo
title: cleo
sidebar_background_image: bg.jpg

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Cleo Engineer Notes

description: Stylish Jekyll Theme
author:
  name: cleo
  email: second934@gmail.com
  github: cleoliu
  twitter: 
  pinterest: 
  linkedin: cleo-l-770422130
  bio: Writing and Learning!
  email_md5: pexels-photo-1449638.jpeg

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:

plugins:
  - jekyll-paginate
